# Dependabot version updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      actions:
        applies-to: version-updates
        patterns:
          - "*"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      actions:
        applies-to: version-updates
        patterns:
          - "*"

  # Maintain Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      types-dependencies:
        applies-to: version-updates
        patterns:
          - "types-*"
          - "mypy"
      tests-dependencies:
        applies-to: version-updates
        patterns:
          - "pytest*"
      patch-dependencies:
        applies-to: version-updates
        update-types:
          - "patch"
