services:
  hyperion-db:
    image: postgres
    container_name: hyperion-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGTZ: ${POSTGRES_TZ}
    ports:
      - 5432:5432
    volumes:
      - hyperion_db_data:/var/lib/postgresql

  hyperion-redis:
    image: redis
    container_name: hyperion-redis-dev
    restart: unless-stopped
    ports:
      - 6379:6379

volumes:
  hyperion_db_data:
