name: Publish Preprod

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy in preprod"
        required: true
        default: "main"
      preprod_env:
        description: "Preprod environment"
        required: true
        type: choice
        options:
          - preprod-1
          - preprod-2
          - preprod-3
          - preprod-4
          - preprod-5
          - preprod-6
          - preprod-7
          - preprod-8
          - preprod-9
        default: "preprod-1"

jobs:
  build-and-deploy-preprod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.6.0
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5.8.0
        with:
          images: ${{ secrets.DOCKER_REGISTRY_URL }}/hyperion
          tags: |
            type=raw,value=${{ github.event.inputs.preprod_env }}
            type=raw,value=preprod-latest,enable={{is_default_branch}}
            type=sha,prefix={{branch}}-
          labels: |
            preprod.environment=${{ github.event.inputs.preprod_env }}
            preprod.branch=${{ github.event.inputs.branch }}

      - name: Build and push preprod image
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          platforms: linux/amd64 #,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=registry,ref=${{ secrets.DOCKER_REGISTRY_URL }}/hyperion:${{ github.event.inputs.preprod_env }}
            type=registry,ref=${{ secrets.DOCKER_REGISTRY_URL }}/hyperion:alpha
            type=registry,ref=${{ secrets.DOCKER_REGISTRY_URL }}/hyperion:latest
          cache-to: type=registry,ref=${{ secrets.DOCKER_REGISTRY_URL }}/${{ github.repository }}/cache,mode=max
